"""Creates tables and seeds sample questions for local development.

Run with: python -m app.database.seed
"""

from app.database.connection import Base, SessionLocal, engine
from app.models.question import AnswerOption, Difficulty, Question

SAMPLE_QUESTIONS = [
    # Python Basics
    dict(
        topic="Python Basics",
        question_text="What is the output of `type([])` in Python?",
        option_a="<class 'list'>",
        option_b="<class 'array'>",
        option_c="<class 'tuple'>",
        option_d="<class 'dict'>",
        correct_answer=AnswerOption.A,
        explanation="`[]` creates an empty list, and `type()` returns its class, `list`.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Python Basics",
        question_text="Which keyword is used to define a function in Python?",
        option_a="function",
        option_b="def",
        option_c="func",
        option_d="lambda",
        correct_answer=AnswerOption.B,
        explanation="`def` introduces a function definition; `lambda` creates anonymous functions instead.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Python Basics",
        question_text="What does the `self` parameter refer to inside an instance method?",
        option_a="The class itself",
        option_b="The parent class",
        option_c="The current instance of the class",
        option_d="A global variable",
        correct_answer=AnswerOption.C,
        explanation="`self` is a reference to the instance the method is being called on.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Python Basics",
        question_text="What is the result of `3 // 2` in Python?",
        option_a="1.5",
        option_b="1",
        option_c="2",
        option_d="1.0",
        correct_answer=AnswerOption.B,
        explanation="`//` performs floor (integer) division, so `3 // 2` evaluates to `1`.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Python Basics",
        question_text="Which of these is mutable in Python?",
        option_a="tuple",
        option_b="str",
        option_c="frozenset",
        option_d="list",
        correct_answer=AnswerOption.D,
        explanation="Lists can be modified in place; tuples, strings, and frozensets are immutable.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Python Basics",
        question_text="What does a decorator in Python primarily do?",
        option_a="Deletes a function",
        option_b="Wraps a function to extend its behavior without modifying its code",
        option_c="Converts a function into a class",
        option_d="Compiles Python to machine code",
        correct_answer=AnswerOption.B,
        explanation="A decorator takes a function and returns a new function that adds behavior around it.",
        difficulty=Difficulty.HARD,
    ),
    dict(
        topic="Python Basics",
        question_text="What exception is raised when dividing an integer by zero?",
        option_a="ValueError",
        option_b="ArithmeticError",
        option_c="ZeroDivisionError",
        option_d="TypeError",
        correct_answer=AnswerOption.C,
        explanation="Python raises `ZeroDivisionError`, a subclass of `ArithmeticError`, for `n / 0`.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Python Basics",
        question_text="What will `list(range(5))[-1]` return?",
        option_a="5",
        option_b="4",
        option_c="0",
        option_d="IndexError",
        correct_answer=AnswerOption.B,
        explanation="`range(5)` produces 0..4, and index `-1` returns the last element, `4`.",
        difficulty=Difficulty.MEDIUM,
    ),
    # Data Structures
    dict(
        topic="Data Structures",
        question_text="What is the average time complexity of searching in a balanced binary search tree?",
        option_a="O(1)",
        option_b="O(log n)",
        option_c="O(n)",
        option_d="O(n log n)",
        correct_answer=AnswerOption.B,
        explanation="A balanced BST halves the search space at each step, giving O(log n) search.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Data Structures",
        question_text="Which data structure uses LIFO (Last In, First Out) ordering?",
        option_a="Queue",
        option_b="Stack",
        option_c="Linked List",
        option_d="Heap",
        correct_answer=AnswerOption.B,
        explanation="A stack pops the most recently pushed element first, i.e. LIFO.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Data Structures",
        question_text="What is the worst-case time complexity of inserting into a hash table?",
        option_a="O(1)",
        option_b="O(log n)",
        option_c="O(n)",
        option_d="O(n^2)",
        correct_answer=AnswerOption.C,
        explanation="With many hash collisions, insertion degrades to O(n) in the worst case, though it is O(1) on average.",
        difficulty=Difficulty.HARD,
    ),
    dict(
        topic="Data Structures",
        question_text="Which traversal visits a binary tree's nodes in sorted order for a BST?",
        option_a="Pre-order",
        option_b="Post-order",
        option_c="In-order",
        option_d="Level-order",
        correct_answer=AnswerOption.C,
        explanation="In-order traversal (left, root, right) visits BST nodes in ascending sorted order.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Data Structures",
        question_text="What underlying structure is typically used to implement a priority queue efficiently?",
        option_a="Array",
        option_b="Heap",
        option_c="Stack",
        option_d="Singly linked list",
        correct_answer=AnswerOption.B,
        explanation="A binary heap gives O(log n) insert and extract-min/max, ideal for priority queues.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Data Structures",
        question_text="What does Big-O notation describe?",
        option_a="Exact runtime in seconds",
        option_b="The upper bound of an algorithm's growth rate",
        option_c="Memory address size",
        option_d="The number of lines of code",
        correct_answer=AnswerOption.B,
        explanation="Big-O describes how runtime or space scales as input size grows, ignoring constants.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Data Structures",
        question_text="In a singly linked list, what is the time complexity to access the k-th element?",
        option_a="O(1)",
        option_b="O(log n)",
        option_c="O(k)",
        option_d="O(n^2)",
        correct_answer=AnswerOption.C,
        explanation="You must traverse node by node from the head, so accessing index k takes O(k) time.",
        difficulty=Difficulty.MEDIUM,
    ),
    # Databases
    dict(
        topic="Databases",
        question_text="Which SQL clause is used to filter rows after aggregation (GROUP BY)?",
        option_a="WHERE",
        option_b="HAVING",
        option_c="FILTER",
        option_d="ORDER BY",
        correct_answer=AnswerOption.B,
        explanation="`HAVING` filters grouped results, while `WHERE` filters rows before grouping.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Databases",
        question_text="What does ACID stand for in database transactions?",
        option_a="Atomicity, Consistency, Isolation, Durability",
        option_b="Accuracy, Consistency, Integration, Durability",
        option_c="Atomicity, Concurrency, Isolation, Data-safety",
        option_d="Availability, Consistency, Isolation, Durability",
        correct_answer=AnswerOption.A,
        explanation="ACID guarantees are Atomicity, Consistency, Isolation, and Durability.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Databases",
        question_text="Which type of SQL join returns only rows with matches in both tables?",
        option_a="LEFT JOIN",
        option_b="RIGHT JOIN",
        option_c="INNER JOIN",
        option_d="FULL OUTER JOIN",
        correct_answer=AnswerOption.C,
        explanation="`INNER JOIN` returns only the rows where the join condition matches in both tables.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Databases",
        question_text="What is the purpose of a primary key in a relational table?",
        option_a="To speed up all queries automatically",
        option_b="To uniquely identify each row in the table",
        option_c="To store foreign data",
        option_d="To define the table's storage engine",
        correct_answer=AnswerOption.B,
        explanation="A primary key uniquely identifies each row and cannot contain NULL or duplicate values.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Databases",
        question_text="What normal form eliminates transitive dependencies on the primary key?",
        option_a="1NF",
        option_b="2NF",
        option_c="3NF",
        option_d="BCNF",
        correct_answer=AnswerOption.C,
        explanation="Third normal form (3NF) requires that non-key attributes depend only on the key, removing transitive dependencies.",
        difficulty=Difficulty.HARD,
    ),
    dict(
        topic="Databases",
        question_text="What does an index primarily improve in a database?",
        option_a="Write throughput",
        option_b="Read/query performance",
        option_c="Disk compression",
        option_d="Backup speed",
        correct_answer=AnswerOption.B,
        explanation="Indexes speed up lookups and queries at the cost of extra storage and slower writes.",
        difficulty=Difficulty.MEDIUM,
    ),
    # Web Development
    dict(
        topic="Web Development",
        question_text="Which HTTP status code indicates a successful resource creation?",
        option_a="200",
        option_b="201",
        option_c="301",
        option_d="404",
        correct_answer=AnswerOption.B,
        explanation="`201 Created` signals that a request successfully created a new resource.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Web Development",
        question_text="What does REST stand for?",
        option_a="Representational State Transfer",
        option_b="Remote State Transmission",
        option_c="Relational State Transfer",
        option_d="Representational Service Technology",
        correct_answer=AnswerOption.A,
        explanation="REST stands for Representational State Transfer, an architectural style for web APIs.",
        difficulty=Difficulty.EASY,
    ),
    dict(
        topic="Web Development",
        question_text="In React, what hook lets you run side effects after render?",
        option_a="useState",
        option_b="useEffect",
        option_c="useMemo",
        option_d="useContext",
        correct_answer=AnswerOption.B,
        explanation="`useEffect` runs side effects (data fetching, subscriptions) after the component renders.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Web Development",
        question_text="Which HTTP method is idempotent and used to fully replace a resource?",
        option_a="POST",
        option_b="PATCH",
        option_c="PUT",
        option_d="GET",
        correct_answer=AnswerOption.C,
        explanation="`PUT` replaces the target resource entirely and is idempotent (repeating it has the same effect).",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Web Development",
        question_text="What does CORS stand for?",
        option_a="Cross-Origin Resource Sharing",
        option_b="Client-Origin Request Service",
        option_c="Cross-Object Rendering System",
        option_d="Cascading Origin Resource Style",
        correct_answer=AnswerOption.A,
        explanation="CORS (Cross-Origin Resource Sharing) governs how browsers allow requests across different origins.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Web Development",
        question_text="What is the primary purpose of TypeScript over plain JavaScript?",
        option_a="Faster runtime execution",
        option_b="Static typing checked at compile time",
        option_c="Built-in database access",
        option_d="Automatic CSS generation",
        correct_answer=AnswerOption.B,
        explanation="TypeScript adds static type checking on top of JavaScript, catching type errors before runtime.",
        difficulty=Difficulty.EASY,
    ),
    # Operating Systems
    dict(
        topic="Operating Systems",
        question_text="What is a deadlock?",
        option_a="A process that never terminates",
        option_b="A situation where processes wait forever for resources held by each other",
        option_c="A memory leak",
        option_d="A crashed kernel thread",
        correct_answer=AnswerOption.B,
        explanation="A deadlock occurs when a set of processes are each waiting for a resource held by another in the set.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Operating Systems",
        question_text="What is the main purpose of virtual memory?",
        option_a="To increase CPU clock speed",
        option_b="To let processes use more memory than physically available and isolate address spaces",
        option_c="To compress files on disk",
        option_d="To speed up network requests",
        correct_answer=AnswerOption.B,
        explanation="Virtual memory abstracts physical memory, enabling isolation and use of more memory than physically installed.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Operating Systems",
        question_text="Which scheduling algorithm can cause starvation of long processes?",
        option_a="Round Robin",
        option_b="First-Come First-Served",
        option_c="Shortest Job First",
        option_d="FIFO",
        correct_answer=AnswerOption.C,
        explanation="Shortest Job First can starve long jobs if shorter jobs keep arriving and are prioritized.",
        difficulty=Difficulty.HARD,
    ),
    dict(
        topic="Operating Systems",
        question_text="What is a race condition?",
        option_a="Two processes finishing at exactly the same time by design",
        option_b="An outcome that depends on the unpredictable timing of concurrent operations",
        option_c="A CPU running faster than expected",
        option_d="A disk read error",
        correct_answer=AnswerOption.B,
        explanation="A race condition happens when the result of concurrent execution depends on non-deterministic timing/ordering.",
        difficulty=Difficulty.MEDIUM,
    ),
    dict(
        topic="Operating Systems",
        question_text="What does a mutex primarily provide?",
        option_a="Mutual exclusion so only one thread accesses a resource at a time",
        option_b="Faster context switching",
        option_c="Automatic memory management",
        option_d="Inter-process file transfer",
        correct_answer=AnswerOption.A,
        explanation="A mutex (mutual exclusion lock) ensures only one thread can hold it, and thus access the guarded resource, at a time.",
        difficulty=Difficulty.EASY,
    ),
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        if db.query(Question).count() > 0:
            print("Questions already seeded, skipping.")
            return
        db.add_all(Question(**data) for data in SAMPLE_QUESTIONS)
        db.commit()
        print(f"Seeded {len(SAMPLE_QUESTIONS)} questions.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
